export const initialSensorInput = {
  sensor_model: "",
  supplier: null,
  glass_lid_type: [],
  spectrum: [],
  shutter_type: [],
  sensor_type: null,
  state: null,
  other_info: "",
  alternative_designation: "",
  pixel_lens_cra: "",
  glass_index: "",
  focal_plane_from_bottom: "",
  glass_lid_thickness: "",
  housing_glass: "",
  optical_center_y: "",
  optical_center_x: "",
  housing_x: "",
  housing_y: "",
  entry_year: "",
  end_of_life: "",
  x_resolution: "",
  y_resolution: "",
  pixel_size: "",
};
