import { SensorInput } from "../../generated/graphql";

export const initialSensorInput: SensorInput = {
  sensor_model: "",
  supplier: "",
  glass_lid_type: [],
  spectrum: [],
  shutter_type: [],
  sensor_type: null,
  state: undefined,
  other_info: "",
  alternative_designation: "",
  pixel_lens_cra: undefined,
  glass_index: "",
  focal_plane_from_bottom: undefined,
  glass_lid_thickness: undefined,
  housing_glass: undefined,
  optical_center_y: undefined,
  optical_center_x: undefined,
  housing_x: undefined,
  housing_y: undefined,
  entry_year: undefined,
  end_of_life: undefined,
  x_resolution: undefined,
  y_resolution: undefined,
  pixel_size: undefined,
};
